### PR TITLE
feat: claim page (HNT-6145)

### PR DESCRIPTION
**Pull request by miguel-nascimento**
its a very huge PR due to the ABIs and because I changed the old `constant/contracts.ts` to wagmi cli codegen, to generate react bindings of contracts

### CODE REVIEW

**Review by jterzis — COMMENTED** [review]
Do we still need AuthorizedClaimer address for base ? I don't see how this will work in Base without it. Any other contracts where we're missing Base address in this pr ?

**Comment by jterzis** [comment]
> Do we still need AuthorizedClaimer address for base ? I don't see how this will work in Base without it. Any other contracts where we're missing Base address in this pr ?

For base, AuthorizedClaimer address should be Base baseRegistry as it is a facet set with ProxyBatchDelegation.

**Comment by miguel-nascimento** [comment]
> Any other contracts where we're missing Base address in this pr ?

For the authorizer we're missing a baseSepolia and base mainnet address. For the claimer one, we do have the baseSepolia, but we're missing the base mainnet address

**Comment by miguel-nascimento** [comment]
> For base, AuthorizedClaimer address should be Base baseRegistry as it is a facet set with ProxyBatchDelegation.

I'll do that in a followup PR

**Review by jterzis — APPROVED** [review]

**Pull request merged**
